// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk28H9L5ssB4Kby9waGAu2ok1rpHRuvnA',
    appId: '1:387655638332:web:34dc007f206eeb4bd71239',
    messagingSenderId: '387655638332',
    projectId: 'calculator-2405',
    authDomain: 'calculator-2405.firebaseapp.com',
    storageBucket: 'calculator-2405.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqh2JdVFtBsEKqJIxgc_i63JsM0HFO3UY',
    appId: '1:387655638332:android:a01ef8f805d2c074d71239',
    messagingSenderId: '387655638332',
    projectId: 'calculator-2405',
    storageBucket: 'calculator-2405.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0e7Q5M24K0tTosgRUEEd_BHQt9ZUazWw',
    appId: '1:387655638332:ios:cf75ab0502ede453d71239',
    messagingSenderId: '387655638332',
    projectId: 'calculator-2405',
    storageBucket: 'calculator-2405.firebasestorage.app',
    iosBundleId: 'com.example.calculadora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0e7Q5M24K0tTosgRUEEd_BHQt9ZUazWw',
    appId: '1:387655638332:ios:cf75ab0502ede453d71239',
    messagingSenderId: '387655638332',
    projectId: 'calculator-2405',
    storageBucket: 'calculator-2405.firebasestorage.app',
    iosBundleId: 'com.example.calculadora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk28H9L5ssB4Kby9waGAu2ok1rpHRuvnA',
    appId: '1:387655638332:web:469be5ee565e6e3ad71239',
    messagingSenderId: '387655638332',
    projectId: 'calculator-2405',
    authDomain: 'calculator-2405.firebaseapp.com',
    storageBucket: 'calculator-2405.firebasestorage.app',
  );
}
